### ISSUE TITLE
"No module named ctrl_pkg.msg"

### ISSUE THREAD

**Issue by nielwestover** [cmasenas/AWS-Deepracer-Gamepad-Control#1]
After sourcing ~/catkin/devel/setup.bash, I run "roslaunch deepracer_cntl joy_cntl.launch". 
I get the following error:
File "/home/deepracer/catkin_ws/src/deepracer_cntl/src/joy_cntl.py", line 4, in <module>
    from ctrl_pkg.msg import ServoCtrlMsg
ImportError: No module named ctrl_pkg.msg

ctrl_pkg is not present in the list of messages when I run "rosmsg list".  I can get it to show up in the list if I source the aws setup.bash file. How can I get it to show up for use with the deepracer_cntl package?

Thanks.
Niel

**Comment by jeffsheets** [comment]
@nielwestover @cmasenas I'm trying this today, and hitting the same `No module named ctrl_pkg.msg`

I've tried a bunch of things but I'm kind of stuck. Were you able to fix this by adding the package somewhere?

**Comment by nielwestover** [comment]
@jeffsheets Sorry I don't remember the exact specifics, but I ended up learning ROS way more than I intended to get it working. I walked through the tutorials to understand how the package system works. I also spent a lot of time following Mark Wolfe's original blog at https://www.wolfe.id.au/2018/12/22/using-aws-deepracer-for-ros-development/. Specifically, I had to add this line to make it work (independent of the package issue): 
$ sudo systemctl restart deepracer-core.service. 

Unfortunately, this github doesn't seem to have all the details. But if you combine it with Mark Wolfe's blog and do some of the ROS tutorials, you'll figure it out after 3 weeks of banging your head like I did...

**Comment by jeffsheets** [comment]
Thanks @nielwestover. After hacking on it yesterday, I definitely learned way more about ROS too... I eventually got it to work by copying the AWS ServoCtrlMsg.msg file into this project and setting up the ROS message generation stuff. I'll clean it up a little and post the code to a fork sometime soon in case anyone else needs it later.

I'm sure there's a way to link to the aws package directly, but I couldn't seem to figure it out....

Anyways, thanks!
